"""datetime image types aangepast

Revision ID: 53460a4577b1
Revises: cc5389363fd5
Create Date: 2026-03-27 15:58:51.453513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53460a4577b1'
down_revision: Union[str, Sequence[str], None] = 'cc5389363fd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("'2026-03-27 14:09:32.78673'::timestamp without time zone"))
    op.alter_column('image', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("'2026-03-27 14:09:32.78673'::timestamp without time zone"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text("'2026-03-27 14:09:32.78673'::timestamp without time zone"))
    op.alter_column('image', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text("'2026-03-27 14:09:32.78673'::timestamp without time zone"))
    # ### end Alembic commands ###
